### ISSUE TITLE
Dragon Attack Crash

### ISSUE THREAD

**Issue by ZephyraNF** [HTTYMD-Team/HTTYMD-Mod#10]
Happens when you have a dragon trained, you hit something. once it goes to kill said mob the game will crash. may be due to the fact that i had 3 dragons trained, but not sure, i also had some other mods installed.
crash report as follows

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/2/15 11:08 AM
Description: Ticking entity

java.lang.NoClassDefFoundError: org/apache/commons/lang3/RandomUtils
    at com.httymd.util.DragonDamageSource.getDirectDamage(DragonDamageSource.java:37)
    at com.httymd.entity.EntityDragon.func_70652_k(EntityDragon.java:86)
    at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:148)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at WorldServerOF.func_72870_g(WorldServerOF.java:347)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.RandomUtils
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 22 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.httymd.util.DragonDamageSource.getDirectDamage(DragonDamageSource.java:37)
    at com.httymd.entity.EntityDragon.func_70652_k(EntityDragon.java:86)
    at net.minecraft.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:148)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
    Entity Type: httymd.NightFury (com.httymd.entity.dragon.EntityNightFury)
    Entity ID: 12550
    Entity Name: Night Fury
    Entity's Exact location: -471.09, 38.00, -30.90
    Entity's Block location: World: (-472,38,-31), Chunk: (at 8,2,1 in -30,-2; contains blocks -480,0,-32 to -465,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Entity's Momentum: -0.40, -0.08, 0.57
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: HTTYMD Server Map
    All players: 1 total; [EntityPlayerMP['CodyMMR'/321, l='HTTYMD Server Map', x=-476.34, y=38.00, z=-29.04]]
    Chunk stats: ServerChunkCache: 549 Drop: 0
    Level seed: 27594263
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-316,63,126), Chunk: (at 4,3,14 in -20,7; contains blocks -320,0,112 to -305,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 7012913 game time, 110134 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 122736 (now: false), thunder time: 83690 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 577388384 bytes (550 MB) / 1217040384 bytes (1160 MB) up to 4187619328 bytes (3993 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_B5 6 mods loaded, 6 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    httymd{1.0.0} [How to Train Your Minecraft Dragon](HTTYMD-1.7.10-10.13.2.1230F-1.0R.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['CodyMMR'/321, l='HTTYMD Server Map', x=-476.34, y=38.00, z=-29.04]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Spartan322** [comment]
This is odd, will attempt to find and fix
